### ISSUE TITLE
Customizing the code to a different gimbal/camera setup

### ISSUE THREAD

**Issue by ghost** [ChristofSchmid/GimbalOverMavlink#1]
I'd like to customize this repo to enable mavlink communication between the following camera.
https://www.foxtechfpv.com/seeker-10-v2-hd-10x-optical-zoom-camera-with-3-axis-gimbal.html
would you be able to give me some pointers on how to do it.

**Comment by ChristofSchmid** [comment]
[cid:42EA524B-311F-47DF-AF12-ECABF9468DAE]
Get the interface doc and implement it in the Mavlink section.

Cheers
Christof

AAA Immobilien AG
Seestrasse 81
8700 Küsnacht

Sent from my mobile phone.

Am 03.10.2020 um 05:39 schrieb Yuthika Sagarage <notifications@github.com>:

﻿

I'd like to customize this repo to enable mavlink communication between the following camera.
https://www.foxtechfpv.com/seeker-10-v2-hd-10x-optical-zoom-camera-with-3-axis-gimbal.html
would you be able to give me some pointers on how to do it.
